[project]
name = "cba-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipumspy>=0.8.2",
    "matplotlib>=3.10.9",
    "paddleocr>=3.6.0",
    "pandas>=2.3.0",
    "pytest>=8.4.2",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.4.1",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "wordcloud>=1.9.6",
]
